Repository kubernetes/system-validators, pull requests merged in 2019-11, with the labels that each got.

#1 push the system validators to the new repository
  go.mod
  go.sum
  validators/cgroup_validator.go
  validators/cgroup_validator_test.go
  validators/docker_validator.go
  validators/docker_validator_test.go
  validators/kernel_validator.go
  validators/kernel_validator_helper.go
  validators/kernel_validator_test.go
  validators/os_validator.go
  validators/os_validator_test.go
  validators/package_validator.go
  validators/package_validator_test.go
  validators/report.go
  validators/types.go
  validators/types_unix.go
  validators/types_windows.go
  validators/validators.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, priority/important-longterm, size/XXL

#3 Add check for docker engine liveness
  validators/docker_validator.go
  validators/docker_validator_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#4 fix undesired update of dependency versions
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/important-soon, size/S

#5 fix misspell build for go 1.13
  hack/verify-spelling.sh
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, size/XS

#6 bump docker engine version to sync with k/k
  validators/docker_validator.go
  validators/docker_validator_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#7 fix docker version in unix types
  validators/types_unix.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
