Repository kubernetes/system-validators, pull requests merged in 2024-11, with the labels that each got.

#43 check unified Mountpoint cgroup version in case user uses cgroupoup v1 on new kernel
  go.mod
  go.sum
  validators/cgroup_validator_linux.go
  validators/cgroup_validator_test.go
Labels: kind/bug, approved, sig/cluster-lifecycle, cncf-cla: yes, sig/node, lgtm, size/M

#47 update OWNERS
  OWNERS
Labels: approved, sig/cluster-lifecycle, cncf-cla: yes, sig/node, size/XS, lgtm

#46 Use `unix.Uname` instead of exec'ing `uname`
  go.mod
  go.sum
  validators/os_validator_unix.go
  validators/package_validator_linux.go
  validators/types_unix.go
Labels: approved, sig/cluster-lifecycle, cncf-cla: yes, sig/node, ok-to-test, lgtm, size/M
